# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

env:
  NAME: "REACT APOD BUILDER"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production
    env:
      REACT_APP_NASA_API_TOKEN: ${{ secrets.REACT_APP_NASA_API_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Print env var
        run: echo "Hello $NAME. $BUILD."
        env:
          BUILD: "We are currently running the Build job"
      - run: npm ci
      - run: npm test
